### PR TITLE
Postman 8.12.4

### PR DESCRIPTION
**Pull request by dheid**
Hey @crazy-max!

How about a new version? 😄

### CODE REVIEW

**Comment by dheid** [comment]
@crazy-max What do you think?

**Review by crazy-max — CHANGES_REQUESTED** [review]
LGTM but revert changes from CHANGELOG, thanks!

**Comment by dheid** [comment]
@crazy-max Done

**Comment by crazy-max** [comment]
https://github.com/portapps/postman-portable/releases/tag/9.1.2-51

**Pull request closed without merging**
